#!/usr/bin/env php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';

/**
 * This example shows how to use the parser to parse an multiple complete JSON
 * objects.
 */

// Create the parser ...
$parser = new Icecave\Duct\Parser;

// Read the entire set of JSON documents ...
$buffer = file_get_contents(__DIR__ . '/input.json');
printf('(Read %d bytes)' . PHP_EOL, strlen($buffer));

// Feed JSON data to the parser and extract parsed values ...
$values = $parser->parse($buffer);

foreach ($values as $value) {
    printf('Parsed value: %s' . PHP_EOL, json_encode($value));
}

echo 'Done' . PHP_EOL;
